import results from '../../../research/v3-results.json';
const pct=(x:number)=>`${(x*100).toFixed(2)}%`;
export default function ReplayReport(){return <main style={{maxWidth:1200,margin:'auto',padding:'48px 24px',color:'#e7e9ef',background:'#10131a',minHeight:'100vh',fontFamily:'sans-serif'}}>
<a href="/">← Agent Arena</a><h1>Audit eksekusi V3</h1>
<p>Simulasi lebih ketat. Belum terbukti siap menghasilkan profit uang asli.</p>
<p>Semua angka memakai ulang data riset V2: BTC sampai 4 Mei 2026 dan ETH sampai 18 April 2026. Ini pengujian eksploratif, bukan holdout baru atau kondisi pasar September 2026. Lima strategi berbasis aturan; inferensi AI dan transaksi nyata belum diuji.</p>
<h2>Apa yang berubah</h2><p>Entry di open berikutnya; stop-loss dan batas drawdown diperiksa sepanjang dua skenario urutan OHLC. Gap dieksekusi pada open, biaya dikenakan pada setiap fill, dan posisi terakhir ditutup pada close terakhir. Dua urutan ini bukan jaminan batas terbaik/terburuk eksekusi tick nyata.</p>
<p>reference: cap 35%; fixed10: cap 10%; risk1: anggaran risiko 1% dibagi stop 10% plus friksi, cap maksimum 35%. Sinyal V2 dibekukan. Total 48 skenario portofolio, masing-masing lima agen; seluruh hasil ditampilkan tanpa memilih pemenang.</p>
<h2>Seluruh hasil setelah biaya</h2><p>Return adalah gabungan lima akun bermodal sama, sepanjang periode, bukan per tahun. Winrate berdasarkan posisi yang sudah ditutup, termasuk penutupan akhir. Fee 80/120 bps per sisi dan slippage 5 bps per sisi adalah asumsi simulasi.</p>
<div style={{overflowX:'auto'}}><table style={{borderCollapse:'collapse',width:'100%'}}><thead><tr>{['Aset','Periode','Cap','Urutan','Fee bps','Return','Menang / tutup','Winrate','DD agen terburuk','Agen halt'].map(x=><th key={x} style={{padding:10,textAlign:'left'}}>{x}</th>)}</tr></thead><tbody>{results.rows.map((r,i)=><tr key={i}>{[r.asset,`${r.start} → ${r.end}`,r.policy,r.path,r.fee,pct(r.return),`${r.wins}/${r.closed}`,r.winrate===null?'—':pct(r.winrate),pct(Math.max(...r.agents.map(a=>a.drawdown))),r.agents.filter(a=>a.halted).length].map((v,j)=><td key={j} style={{padding:10,borderTop:'1px solid #343945'}}>{v}</td>)}</tr>)}</tbody></table></div>
<h2>Kesimpulan yang bisa dipakai</h2><p>Ukuran posisi lebih kecil mengurangi drawdown pada pengujian BTC terkini, tetapi tidak menaikkan profit total. ETH 2022–2023 tetap merugi. Belum ada dasar untuk menjanjikan profit maksimal atau mempromosikan strategi ke uang asli.</p>
<p>Replay mengasumsikan pengawasan barrier terus-menerus. Aplikasi paper hanya memeriksa saat tab aktif, sehingga hasil ini bukan prediksi fill aplikasi. Profil forward tidak diubah otomatis. Untuk mencoba cap 10%, pilih profil Research V2 dan ubah maximum exposure menjadi 10% sebelum memulai simulasi baru.</p>
<h2>Alternatif carry</h2><p>Membeli spot dan menjual futures punya sumber pendapatan ekonomi, namun funding berubah, dua kaki transaksi menambah biaya, dan posisi futures tetap bisa dilikuidasi. Belum diaktifkan karena tidak tersedia data funding lengkap dan koneksi akun yang diperlukan. <a href="https://www.bis.org/publications/working-paper-1087-crypto-carry">Riset BIS</a> · <a href="https://support.kraken.com/articles/4402283092244-liquidation-faq-derivatives">Mekanisme likuidasi Kraken</a></p>
<p>Metode pembanding: <a href="https://www.freqtrade.io/en/stable/backtesting/">asumsi backtesting Freqtrade</a>. <a href="/research">Laporan V2</a>.</p>
</main>}
