import type {Metadata} from 'next';
import results from '@/research/v2-results.json';
import selection from '@/research/v2-selection.json';
import {Table,TableHeader,TableBody,TableHead,TableRow,TableCell} from '@/components/ui/table';
export const metadata:Metadata={title:'Agent Arena | Laporan Riset V2',description:'Hasil lengkap strategi harian, biaya, pengujian di luar sampel dan keterbatasannya.'};
const percent=(n:number|null)=>n===null?'—':`${n>=0?'+':''}${(n*100).toFixed(2)}%`;
const rate=(n:number|null)=>n===null?'—':`${(n*100).toFixed(2)}%`;
const source='https://github.com/steve-x-y/freqtrade/tree/codex/agent-arena-20260907/agent-arena/research';
const fileSource=source.replace('/tree/','/blob/');
type Row=typeof results.final.agents[number];
function ResultsTable({rows}:{rows:Row[]}){return <Table><TableHeader><TableRow><TableHead>Agen</TableHead><TableHead>Menang / tutup</TableHead><TableHead>Winrate</TableHead><TableHead>Return bersih</TableHead><TableHead>Max DD</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{rows.map(a=><TableRow key={a.id}><TableCell>{a.name}{a.id===selection.selected?' · dipilih awal':''}</TableCell><TableCell>{a.wins} / {a.closed}</TableCell><TableCell>{rate(a.winrate)}</TableCell><TableCell className={a.return>=0?'positive':'negative'}>{percent(a.return)}</TableCell><TableCell>{rate(a.maxDrawdown)}</TableCell><TableCell>{a.halted?'Halt':'Tidak halt'}</TableCell></TableRow>)}</TableBody></Table>;}
export default function ResearchReport(){
 const pulse=results.final.agents.find(a=>a.id===selection.selected)!;
 return <main className="research-report" lang="id">
  <nav><a href="/">← Kembali ke arena</a><a href={source}>Sumber &amp; reproduksi ↗</a></nav>
  <header><div className="report-kicker">AGENT ARENA / RESEARCH V2 / 7 SEPTEMBER 2026</div><p><a href="/research/v3">Lihat audit eksekusi V3: stop intrabar dan ukuran posisi</a></p><h1>Lebih selektif.<br/>Belum terbukti unggul.</h1><p className="report-lead">Lima strategi harian menghasilkan profit historis, tetapi belum memenuhi kriteria bukti untuk dipakai dengan uang asli. Profit maksimum belum tercapai dan tidak bisa dijanjikan.</p></header>
  <section className="report-metrics" aria-label="Ringkasan final test"><div><span>Return gabungan</span><strong>{percent(results.final.aggregate.return)}</strong><small>Kumulatif, bukan per bulan</small></div><div><span>Winrate gabungan</span><strong>{rate(results.final.aggregate.winrate)}</strong><small>{results.final.aggregate.wins} menang / {results.final.aggregate.closed} transaksi tertutup</small></div><div><span>Lolos seluruh gerbang bukti</span><strong>{results.acceptedForFurtherPaperResearch.length} / 5</strong><small>Tetap eksperimen paper</small></div></section>
  <p className="report-callout">Periode uji akhir: <strong>1 Januari 2024–4 Mei 2026</strong>. Modal simulasi 50.000 menjadi {(50000*(1+results.final.aggregate.return)).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})} USDT. Hasil lama 11,82% winrate memakai periode dan konfigurasi berbeda; bukan pembanding setara untuk mengiklankan peningkatan winrate.</p>
  <section><h2>01 / Apa yang berubah</h2><p>V2 membuat keputusan dari candle harian, memasukkan friksi pada ambang masuk dan menunggu tiga hari setelah keluar. Tidak ada leverage, short, martingale atau averaging down. Parameter berikut adalah hipotesis, bukan angka optimum yang dibuktikan penelitian.</p><Table><TableHeader><TableRow><TableHead>Agen</TableHead><TableHead>Aturan harian</TableHead></TableRow></TableHeader><TableBody><TableRow><TableCell>Atlas</TableCell><TableCell>MA20/100, penyaring rezim MA200, ambang masuk berbasis biaya.</TableCell></TableRow><TableRow><TableCell>Nova</TableCell><TableCell>RSI14 di bawah 35 hanya ketika MA50/200 dan harga menunjukkan tren naik; keluar di atas 60 atau saat rezim patah.</TableCell></TableRow><TableRow><TableCell>Pulse</TableCell><TableCell>Momentum 28 hari, MA200, ambang momentum dua kali friksi pulang-pergi.</TableCell></TableRow><TableRow><TableCell>Vex</TableCell><TableCell>Breakout high 55 hari sebelumnya ditambah buffer biaya; keluar di bawah low 20 hari sebelumnya.</TableCell></TableRow><TableRow><TableCell>Sage</TableCell><TableCell>Dua dari tiga suara tren: MA50/200, momentum28, harga/MA100; setengah alokasi.</TableCell></TableRow></TableBody></Table><p>Ambang friksi bukan perkiraan profit. Profil V2 memakai stop observasi 10%, berbeda dari stop 5% versi lama. Jadi perubahan hasil tidak boleh diatribusikan hanya ke sinyal baru.</p></section>
  <section><h2>02 / Apa kata bukti primer</h2><p><a href="https://link.springer.com/article/10.1007/s10479-019-03357-1">Hudson &amp; Urquhart (2019/2021)</a> menemukan keberhasilan teknikal historis, tetapi aturan Bitcoin terbaik justru negatif pada uji Januari–Juni 2018. <a href="https://osuva.uwasa.fi/bitstreams/ffee5cb1-92a8-443e-a117-cbaacd8a1028/download">Grobys &amp; Sapkota (2019)</a> juga tidak menemukan signifikansi konvensional pada strategi momentum yang mereka teliti atas 143 kripto. Horizon dan asumsi mereka berbeda dari aplikasi ini.</p><p><a href="https://www.davidhbailey.com/dhbpapers/overfit-tools.pdf">Bailey dkk. (2015)</a> menunjukkan bahaya mencoba banyak variasi lalu memilih hasil terbaik. Karena itu lima kandidat dipatok sebelum evaluasi, tanpa optimasi ulang setelah final test dibuka. Paper tidak membuktikan bahwa lebih banyak agent atau LLM otomatis memberi keunggulan.</p><p><a href="https://www.kraken.com/features/fee-schedule">Jadwal resmi Kraken</a> yang dibaca 7 September 2026 menampilkan taker tingkat awal 0,80% per sisi. Uji utama menggunakan biaya tetap tersebut, tanpa mengasumsikan diskon volume. Tarif akun sebenarnya bisa berbeda.</p></section>
  <section><h2>03 / Pemisahan pengembangan dan pengujian</h2><Table><TableHeader><TableRow><TableHead>Tahap</TableHead><TableHead>Data / keputusan</TableHead></TableRow></TableHeader><TableBody><TableRow><TableCell>Pengembangan</TableCell><TableCell>2018–2021, rekening baru tiap tahun; 2018 parsial karena 201 hari pemanasan. Skor median return tahunan dikurangi separuh drawdown tahunan terburuk memilih Pulse.</TableCell></TableRow><TableRow><TableCell>Validasi</TableCell><TableCell>2022–2023, rekening kontinu baru, aturan tidak berubah. Gabungan {percent(results.validation.aggregate.return)}, winrate {rate(results.validation.aggregate.winrate)} ({results.validation.aggregate.wins}/{results.validation.aggregate.closed}).</TableCell></TableRow><TableRow><TableCell>Uji akhir</TableCell><TableCell>2024–4 Mei 2026, rekening kontinu baru. Tidak memilih ulang berdasarkan pemenang tahap ini.</TableCell></TableRow><TableRow><TableCell>Robustness</TableCell><TableCell>Biaya 10/40/80/120bps, keterlambatan ekstra satu hari, rekening baru per tahun, dan ETH sebagai pembanding pasar tanpa seleksi ulang.</TableCell></TableRow></TableBody></Table><p>Seluruh rekening memakai 10.000 unit, batas alokasi masuk 35% (Sage 17,5%), stop observasi 10% dan drawdown halt 10%. Alokasi dapat berubah mengikuti harga, bukan batas eksposur yang diseimbangkan terus-menerus. Halt permanen dalam setiap rekening uji, bukan direset untuk menghapus kerugian.</p></section>
  <section><h2>04 / Hasil semua kandidat</h2><ResultsTable rows={results.final.agents}/><p>Max DD di tabel adalah penurunan maksimum masing-masing rekening pada observasi harian, bukan drawdown gabungan. Lima agen memperdagangkan aset sama; transaksi mereka bukan observasi independen.</p><p className="report-callout"><strong>Jangan hanya memilih angka tertinggi.</strong> Atlas adalah pemenang setelah hasil akhir terlihat. Pulse adalah kandidat yang benar-benar dipilih sebelumnya: {percent(pulse.return)}, {pulse.wins}/{pulse.closed} menang, dan akhirnya halt. Sage 75% hanya berasal dari 3 kemenangan/4 transaksi, termasuk satu penutupan paksa pada akhir pengujian.</p></section>
  <section><h2>05 / Profit tidak sama dengan keunggulan</h2><Table><TableHeader><TableRow><TableHead>Pembanding</TableHead><TableHead>Return</TableHead><TableHead>Max DD observasi</TableHead></TableRow></TableHeader><TableBody><TableRow><TableCell>Kas, tanpa bunga</TableCell><TableCell>0,00%</TableCell><TableCell>0,00%</TableCell></TableRow><TableRow><TableCell>Buy-and-hold, 35% modal awal</TableCell><TableCell>{percent(results.final.benchmarks.initial35.return)}</TableCell><TableCell>{rate(results.final.benchmarks.initial35.maxDrawdown)}</TableCell></TableRow><TableRow><TableCell>Buy-and-hold, 100% modal awal</TableCell><TableCell>{percent(results.final.benchmarks.full.return)}</TableCell><TableCell>{rate(results.final.benchmarks.full.maxDrawdown)}</TableCell></TableRow></TableBody></Table><p>Benchmark memasukkan biaya masuk dan keluar, tetapi tanpa stop atau halt. Alokasi dibiarkan berubah bersama harga, sehingga bukan pembanding setara risiko. V2 membatasi drawdown observasi lebih kecil, tetapi belum mengalahkan return buy-and-hold tersebut.</p></section>
  <section><h2>06 / Stress test: tampilkan yang buruk juga</h2><Table><TableHeader><TableRow><TableHead>Fee per sisi</TableHead><TableHead>Return gabungan</TableHead><TableHead>Return Pulse</TableHead></TableRow></TableHeader><TableBody>{results.costs.map(r=><TableRow key={r.feeBps}><TableCell>{(r.feeBps/100).toFixed(2)}%{r.feeBps===80?' · utama':''}</TableCell><TableCell>{percent(r.aggregate.return)}</TableCell><TableCell>{percent(r.agents.find(a=>a.id===selection.selected)!.return)}</TableCell></TableRow>)}</TableBody></Table><p>Ambang sinyal tetap memakai 80bps; biaya eksekusi berubah. Biaya memengaruhi basis stop, posisi dan waktu halt, sehingga hasil tidak selalu monoton. Pass awal yang sekaligus mengubah ambang sinyal diperbaiki karena mencampur dua efek; bukan seleksi ulang kandidat.</p><p>Eksekusi terlambat satu hari justru membuat Pulse +12,16%. Perbedaan besar itu menunjukkan sensitivitas timing, bukan alasan mengganti aturan ke versi yang tampak lebih menguntungkan. Uji ETH gabungan {percent(results.external.aggregate.return)}, {results.external.aggregate.wins}/{results.external.aggregate.closed} menang hingga 18 April 2026, tidak membuktikan aset lain lebih baik.</p><Table><TableHeader><TableRow><TableHead>Rekening baru tiap tahun</TableHead><TableHead>Return gabungan</TableHead><TableHead>Return Pulse</TableHead></TableRow></TableHeader><TableBody>{results.years.map(y=><TableRow key={y.label}><TableCell>{y.label.slice(0,4)}{y.label.startsWith('2026')?' · sampai 4 Mei':''}</TableCell><TableCell>{percent(y.aggregate.return)}</TableCell><TableCell>{percent(y.agents.find(a=>a.id===selection.selected)!.return)}</TableCell></TableRow>)}</TableBody></Table><p className="report-callout">Rekening baru pada 2025: <strong>Pulse −10,01%</strong>, gabungan −1,61%. Pada rekening kontinu 2024–2026 beberapa agen sudah halt di 2024. Jadi hasil positif keseluruhan bukan pendapatan yang terus berjalan. Rekening tahunan tidak boleh dijumlahkan sebagai rekening kontinu.</p></section>
  <section><h2>07 / Ketidakpastian dan kualitas data</h2><p>Bootstrap return harian Pulse dalam blok 14 hari, 1.000 replikasi: rentang deskriptif sekitar −19,28% sampai +37,09%. Ini mengacak return yang sudah terjadi, bukan mensimulasikan ulang respons stop/halt pada pasar baru atau uji signifikansi setelah seleksi. Wilson winrate Pulse sekitar 3,62%–62,45%. Sampelnya terlalu kecil untuk menganggap 20% atau 75% sebagai winrate stabil.</p><p>BTC memakai {results.audit.btc.usedRows.toLocaleString('id-ID')} candle harian dari 17 Agustus 2017 hingga 4 Mei 2026; ETH {results.audit.eth.usedRows.toLocaleString('id-ID')} hingga 18 April 2026. Baris terakhir masing-masing dibuang. Audit tidak menemukan duplikat, gap harian atau OHLC invalid. Sebanyak {results.audit.crossCheck.checked.toLocaleString('id-ID')} hari OHLC BTC cocok dengan mirror kedua.</p><p>Data adalah <a href="https://github.com/marek3993/trendatlas-crypto/blob/main/data/ohlcv/BTCUSDT_1d.csv">mirror Binance pihak ketiga</a>, bukan data asli bursa yang sudah kami sertifikasi. <a href="https://github.com/Ruhguevara/Algorithmic_trading/blob/main/files/BTCUSDT_1d.csv">Cross-check</a> hanya mencakup overlap lama. Dua sumber lain ditolak karena generated atau mencurigakan. <a href="https://github.com/binance/binance-public-data">Binance menyediakan arsip resmi dengan checksum</a>, tetapi akses langsung lingkungan kerja dibatalkan kontrol jaringan; tidak dicoba melewatinya. Sumber mirror diambil melalui koneksi GitHub yang tersedia.</p></section>
  <section><h2>08 / Batas simulasi dan keputusan</h2><p>Sinyal hanya menggunakan candle yang sudah selesai, fill pada open berikutnya. Slippage 0,05% per sisi dan fee utama 0,80% per sisi. Stop diperiksa pada open harian, bukan intrabar; kerugian dapat melampaui ambang. Posisi tersisa dilikuidasi pada open observasi terakhir, termasuk biaya keluar. Tombol backtest aplikasi tetap mark-to-market tanpa likuidasi akhir, sehingga bisa berbeda.</p><p>Sesi forward memeriksa risiko lebih sering saat tab aktif, tidak identik dengan observasi harian penelitian. Tidak termasuk biaya AI, pajak, market impact, partial fills, infrastruktur atau risiko USDT/USD. Mode AI, broker live dan feed produksi belum diuji; tidak ada order uang asli atau scheduler 24/7 yang ditambahkan.</p><p><strong>Tidak ada kandidat lolos semua gerbang:</strong> validasi/final positif, profit factor keduanya di atas 1, minimal 10 transaksi tertutup pada masing-masing periode, dan final stress biaya tinggi positif. Sepuluh transaksi hanya penyaring minimal, bukan sertifikasi statistik.</p><p>20 tes lolos: 19 tes unit/adapter, termasuk no-lookahead, cooldown, warmup, friksi, akuntansi dan pemilihan beku, ditambah satu tes rendering laporan di server untuk memeriksa angka dan tautan. TypeScript dan build produksi diperiksa. QA visual browser tidak dilakukan; runtime jaringan dan feed produksi belum diuji ulang setelah akses langsung terhenti.</p><p>Kesimpulan: gunakan V2 hanya sebagai eksperimen paper. Riset dihentikan setelah bukti primer, kontra-bukti dan kandidat beku cukup untuk menilai klaim. Mengoptimasi lagi pada final test yang sudah dibuka bisa mengejar kebetulan. Pembuktian berikutnya perlu forward paper, bukan leverage lebih besar.</p></section>
  <section><h2>09 / Buka eksperimen dan periksa hasilnya</h2><p>Di arena, pilih <strong>Review V2 settings</strong>. Sesi lama tidak diubah; ekspor sebelum membuat sesi baru jika ingin mencoba profil tersebut. Pengaturan yang berbeda atau mode AI berarti eksperimen berbeda.</p><div className="report-links"><a href="/">Buka arena →</a><a href={fileSource+'/EXPERIMENT-V2.md'}>Protokol eksperimen ↗</a><a href={fileSource+'/v2-selection.json'}>Pemilihan sebelum uji ↗</a><a href={fileSource+'/v2-results.json'}>Semua angka &amp; audit ↗</a><a href={fileSource+'/run-v2.mjs'}>Kode pengujian ↗</a><a href={fileSource+'/fetch-v2-data.py'}>Dataset yang dipatok ↗</a></div></section>
  <footer>Agent Arena · Penelitian historis, bukan janji profit atau rekomendasi membeli aset.</footer>
 </main>;
}
